"""empty message

Revision ID: 4a87c1a7e43f
Revises: 6f1fb47131b3
Create Date: 2026-02-14 23:33:29.179544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a87c1a7e43f'
down_revision = '6f1fb47131b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
